### ISSUE TITLE
Forms with multiple submit buttons

### ISSUE THREAD

**Issue by francma** [nittro/nittro#2]
`$form->addSubmit('submit')->onClick[] = [$this, 'doSubmit'];`
`$form->addSubmit('save')->onClick[] = [$this, 'doSave'];`
Both buttons trigger `doSave()`, with last button added to form as an argument.

`$form->onSubmit[] = [$this, 'formSubmit'];`
Triggers `formSubmit()` with last button added to form as an argument.

Tested on https://github.com/nittro/application/tree/master/examples

**Comment by jahudka** [comment]
// this really belongs to nittro/application issues, not here.. just sayin' :-)

Mea culpa, that was supposed to work, sorry about that. Fixed in nittro/application v1.9.14 which just went up; in nittro/nittro the updated builds in dev-master already include this fix, but a new release will have to wait a couple of hours because I'm working on something else here.

Thanks for the report!
