### ISSUE TITLE
Reset or redirect after form submit

### ISSUE THREAD

**Issue by misaon** [nittro/nittro#24]
Its a bug or feature? I have code like this:

```
class PageFormFactory
{
	use Nette\SmartObject;

	/**
	 * @var FormFactory
	 */
	private $factory;

	/**
	 * @var UserManager
	 */
	private $userManager;

	/**
	 * @var PageManager
	 */
	private $pageManager;



	public function __construct(FormFactory $factory, UserManager $userManager, PageManager $pageManager)
	{
		$this->factory = $factory;
		$this->userManager = $userManager;
		$this->pageManager = $pageManager;
	}


	/**
	 * @param callable $onSuccess
	 * @param callable $onFail
	 * @return Form
	 */
	public function create(callable $onSuccess, callable $onFail): Form
	{
		$form = $this->factory->create();

		$form->addText('title')
			->setRequired();
		$form->addTextArea('content');
		$form->addSubmit('send');

		$form->onSuccess[] = function (Form $form) use ($onSuccess, $onFail) {
			try {
				$user = $this->userManager->getLoggedUser();

				$values = $form->getValues();

				$page = new Entities\Page();
				$page->setTitle($values->title);
				$page->setContent($values->content);
				$page->setCreatedBy($user);

				$this->pageManager->add($page);

				$onSuccess();
			} catch (\Exception $e) {
				$onFail($e);
			}
		};

		return $form;
	}
}
```

And presenter like this:

```
class PagePresenter extends LoggedPresenter
{


	/**
	 * @var PageFormFactory
	 */
	private $pageFormFactory;


	public function __construct(PageFormFactory $pageFormFactory)
	{
		parent::__construct();

		$this->pageFormFactory = $pageFormFactory;
	}


	protected function createComponentPageCreateForm(): Form
	{
		return $this->pageFormFactory->create(function () {

			$this->presenter->flashMessage('Stránka byla vytvořena!', 'success');
			$this->postGet('this');
			$this->redrawDefault(true);

		}, function (\Exception $e) {
			print_r($e->getMessage());
			die();
		});
	}
}
```

I have two questions.

1. Redirect to other presenter via postGet() not work for me. Can i do it, how?
2. If i submit form and success callback is called, after redraw snippets form not reset fields. How can i call this feature?

Thanks a lot for answer, Nittro is future for my development 😄

**Comment by jahudka** [comment]
Hi, your code looks okay, regarding your questions:

1) `postGet()` only does an actual redirect if the request *wasn't* made using AJAX for some reason - for AJAX requests it only affects the URL that is pushed onto the browser's history stack. This is mostly useful when you can render the appropriate snippets directly from a signal handler or form success callback (i.e. when an action results in updating a snippet that is already in the page or in adding a dynamic snippet). If you cannot render content directly (e.g. if you'd need to redirect to a different presenter / action), use the regular `redirect()` method and if the request was made using AJAX, Nittro will load the redirect using AJAX as well. In some cases you can save the roundtrip using `forward()` instead - notably if the page you'd redirect to would render the default snippets as usual - but note that in that case the rendered page won't have the correct URL, because Nittro doesn't know about the forward - so this would be useful for requests which have history handling disabled altogether (`data-history="false"` on the form / link that makes the request), or if you implement some custom logic to call `postGet('this')` somewhere in the target presenter of the forward. One way to do this would be to call `postGet('this')` in the base presenter's `afterRender()` method if `$presenter->getRequest()->isMethod(Nette\Application\Request::FORWARD)`, but I'm not using this often enough to be sure it won't do something weird somewhere along the line..

2) Forms should reset automatically if they're submitted successfully. I'm not sure what's happening there - it might be that you have automatic resetting disabled by default (it's an option you can specify in Nittro's bootstrap), or the form could specify the desired behaviour explicitly using `data-reset="true|false"`. Are there any errors in the console after the request is loaded?

**Comment by misaon** [comment]
1. if i call postGet('Page:list') and after this redrawSnippets, snippets and URL are refreshed successfully but content snippet not change to Page:list page.

Response after submit form:

```
{"postGet":true,"url":"/pms-admin/page/list","state":[],"title":"                    Vytvoření stránky\n | PortableCMS\n","snippets":{"snippet--content":"\n            <section class=\"content-header\">\n    <h1>Vytvoření stránky</h1>\n\n    <ol class=\"breadcrumb\">\n        <li><i class=\"fa fa-file-text\"></i> Stránky</li>\n        <li>Seznam</li>\n        <li class=\"active\">Vytvořit</li>\n    </ol>\n            </section>\n\n            <section class=\"content\">\n\n    <div class=\"box\">\n        <div class=\"box-header with-border\">\n            <div class=\"box-title\">\n                <a href=\"/pms-admin/page/list\" class=\"btn btn-default btn-sm\">\n                    <i class=\"fa fa-arrow-left\"></i> Zpět\n                </a>\n            </div>\n\n            <div class=\"box-tools pull-right\">\n                <button type=\"button\" class=\"btn btn-box-tool\" data-widget=\"collapse\"><i class=\"fa fa-minus\"></i>\n                </button>\n            </div>\n        </div>\n\n        <form class=\"form-horizontal\" action=\"/pms-admin/page/create\" method=\"post\" id=\"frm-pageCreateForm\">\n            <div class=\"box-body\">\n                <div class=\"form-group\">\n                    <label class=\"col-sm-2 control-label\" for=\"frm-pageCreateForm-title\">Název</label>\n                    <div class=\"col-sm-10\">\n                        <input class=\"form-control\" type=\"text\" name=\"title\" id=\"frm-pageCreateForm-title\" required data-nette-rules='[{\"op\":\":filled\",\"msg\":\"This field is required.\"}]' value=\"asdfdsfdssfdaasddsasdadsa6dssdaxsaxasa\">\n                    </div>\n                </div>\n                <div class=\"form-group\">\n                    <label class=\"col-sm-2 control-label\" for=\"frm-pageCreateForm-content\">Obsah</label>\n                    <div class=\"col-sm-10\">\n                        <textarea class=\"form-control\" name=\"content\" id=\"frm-pageCreateForm-content\">das</textarea>\n                    </div>\n                </div>\n            </div>\n\n            <div class=\"box-footer\">\n                <button class=\"btn btn-info pull-right\" type=\"submit\" name=\"send\"><i class=\"fa fa-floppy-o\"></i> Uložit</button>\n            </div>\n<input type=\"hidden\" name=\"_token_\" value=\"tnes5xqsvtGsMGxcaJ50tkNfqshneGl30/9fo=\"><input type=\"hidden\" name=\"_do\" value=\"pageCreateForm-submit\"><!--[if IE]><input type=IEbug disabled style=\"display:none\"><![endif]-->\n        </form>\n\n    </div>\n\n            </section>\n"},"flashes":{"flash":[{"message":"Stránka byla vytvořena!","type":"success"}]}}
```
i suggest "snippet--content" have bad code.. i dont know why.

2. Console is clear. I tried set allowFormReset but still not work.

**Comment by misaon** [comment]
Solved.

Problem 1 = nette redirect method throws exception which \Exception catch. in catch isnt any message (blank response => bad debug).

Problem 2 = i changed success callback to:

```php
    $this->flashMessage('Stránka byla vytvořena!', 'success');
    $this->redirect('this');
```

and all Nittro features now run great! :) Sorry for my bad issue.

**Comment by jahudka** [comment]
Glad you worked it out :-) that thing with redirect (as well as forward / sendResponse / sendPayload / sendJson) internally throwing an exception got the better of me a couple of times as well.. I completely missed that in your code.
