### ISSUE TITLE
How use Page.open() method with context parameter

### ISSUE THREAD

**Issue by Kaliver88** [nittro/nittro#27]
I use Page.open() method in my script. I find that context parameter can be used to control transition effect.

Can you give me same example how do it.

``` 
di.getService('page').open(
  {plink this},
  'GET',
  data,
  {
    // control transition effect
  }
);
```

Thanks

**Comment by jahudka** [comment]
Hi, basically the only option at the moment is to use the `transition` context option to either disable transitions altogether (using `transition: false`), or to specify a different selector for elements to transition. Simply specify the `transition` key as one of the properties of the `context` parameter, e.g.:

```javascript
di.getService('page').open({plink this}, 'GET', {
    transition: '#my-spinner'
});
```

Note that Nittro doesn't use `querySelector` / `querySelectorAll` internally because they're quite slow - but for that reason only very basic selectors are supported - `#id`, `.class` and `#id .class` (and of course you can specify multiple selectors separated by a comma).

**Comment by Kaliver88** [comment]
Perfect. Work like a charm.
