### ISSUE TITLE
Ořezává nuly

### ISSUE THREAD

**Issue by JanGalek** [nittro/nittro#4]
# Czech:

Zdravím, narazil jsem na problém, v e-shopu používáme id ve formátu 000000123456789321, když zapnu nittro a dám přidat do košíku, tak na mě vyskočí vyjímka, že index 123456789321 (**oříznuté nuly**) neexistuje (posílám 000000123456789321), což je jasné. Bez nittra funguje vše v pořádku,jde vypnout toto chování ?

odkaz mám ve tvaru: 
example.com/myCategory/?id=**000000165000100017**&do=addToBasket

ovšem po kliknutí, se zpracuje právě bez těch začátečních nul 
example.com/myCategory/?id=**165000100017**&do=addToBasket

EDIT: Zatím jsem to pořešil přes str_pad, ale to se mi nelíbí, když už jednou to posílám, tak to chci taky dostat, navíc to budu muset kontrolovat v celém e-shopu....
# English

Good morning, I get a error, when I send data with zeroes before number, for example **000000165000100017** (link example.com/myCategory/?id=**000000165000100017**&do=addToBasket), then with nittro I get only **165000100017**, but this index I havent in object, which I work. 

Now I must do str_pad($id, 18, "0", STR_PAD_LEFT);, but its not good option, Can you fix it ?

**Comment by jahudka** [comment]
# Czech

Zdravím, chápu, děje se to proto, že nittro interně každé URL parsuje aby např. resolvnulo relativní cesty, zjistilo jestli jde o stejný origin atd., a mimo jiné parsuje i query string aby šlo snadno manipulovat s GET parametry - a snaží se být "chytré" a převést parametry na správný datový typ, takže když něco vypadá jako celé číslo, udělá se parseInt atd. Pak se celé URL včetně query stringu zase poskládá dohromady. Výsledkem je, že nuly na začátku se ztratí. Dočasná oprava se dá implementovat na úrovni nittra, viz níže; trvalé řešení bude poměrně jednoduché (jen budeme trochu přísnější v tom, co považujeme za integer a co ještě necháme jako string), ale vzhledem k tomu, že nittro repozitáře jsou momentálně na půl cesty k verzi 2.0, obávám se, že do distribučních balíčků se dostane právě až s dvojkou.

# English (for posterity)

Hello, I see what the problem is. It's caused by nittro trying to be smart when it parses the URL of the link that was clicked: the URL parser is trying to guess appropriate datatypes for query parameters and since your IDs look like an integer, it will convert them using the parseInt function. Then the URL is put back together and the leading zeroes are lost. A temporary fix can be done on the client side, see below; a long-term solution should be quite easy to implement (we'll just be a bit more strict in what we consider an integer and what we'll leave as a string), but since the master branches of nittro repos are currently a work in progress in order to get nittro 2.0 out, I'm afraid that the long-term fix won't make it before nittro 2.0 is released.

# The temporary fix

Přidejte následující kód na konec vašeho minifikovaného JS: / Append this to your minified JS file:

```
_context.invoke(function(Service, Url) {
    var createRequestOrig = Service.prototype._createRequest;

    Service.prototype._createRequest = function (url, method, data, evt, context) {
        var m = /(?:\?|&)id=(0+\d+)(?:&|$|#)/.exec(url + '');

        if (m) {
            url = Url.from(url);
            url.setParam('id', m[1]);
        }

        return createRequestOrig.call(this, url, method, data, evt, context);
    };
}, {
    Service: 'Nittro.Page.Service',
    Url: 'Utils.Url'
});
```

Dejte vědět, jestli tohle řešení funguje alespoň jako dočasný fix a já tuhle issue zavřu; dlouhodobý fix už mám implementovaný v balíčku Core, ale ještě pár dní potrvá, než se dostanu k tomu, abych to pushnul do masteru.

Let me know if this works at least temporarily and I'll close this issue for the time being; I've already implemented the long-term fix in the Core package, but it'll be a couple of days before I can push it along with other changes.

**Comment by JanGalek** [comment]
Zdravím, úprava je funkční, děkuji.
