### ISSUE TITLE
Invalid tag name 'snippet.id' with latte/latte v2.9.0

### ISSUE THREAD

**Issue by e2221** [nittro/nittro#40]
Hello, I  only inform that there is problem with Nittro after update to latte/latte v2.9.0.
Up to v2.8.3 it´s working well.

**Comment by jahudka** [comment]
hi, thanks for reporting this, I'll look into it!

**Comment by jahudka** [comment]
Hi, David fixed the issue in Latte, so in `latte/latte` v2.9.1 it will work again. Not sure what the best course of action is in the meantime - you could temporarily link to the current commit of `latte/latte` in your `composer.json`, but there may be other changes there, I'm not sure. Or you can temporarily downgrade Latte to 2.8.3 until 2.9.1 is released. In any case I'm closing this because it doesn't require any changes in Nittro for now.

**Comment by e2221** [comment]
Thanks for your support and also for this great libraly.
