### ISSUE TITLE
_context is not defined

### ISSUE THREAD

**Issue by hrach** [nittro/nittro#5]
after downloading the Page zip with dist, the only js starts with _context variable, which basically triggers this error after including into a html document.

**Comment by jahudka** [comment]
Yes, that would happen - I'm halfway to nittro 2.0, one of the many things I'm changing is the build system - used to be that ready-to-use nittro builds with all dependencies were a part of the package, but that was incredibly impractical to maintain, so now the packages only include builds for the package itself and dependencies must be loaded externally. In the future you'll be able to go one of three ways: use bower and the official nittro build tool, or use bower and compile the packages yourself (either from sources or from per-package builds) or download a custom nittro build from the website (I'd like to have a tool similar to what jQuery mobile & others have for custom packages).

For now I'd recommend going for the bleeding-edge `nittro#master`, because it's probably as close to 2.0 API as it gets; the `nittro` package also includes the builder which you can use with [grunt](https://github.com/nittro/grunt) or [gulp](https://github.com/nittro/gulp) to create a custom package to fit your specific needs. You'd need to do something like:

```
bower install --save nittro#master # installs nittro and all dependencies
npm install --save nittro nittro-(gulp|grunt) # whichever you prefer
```
