### ISSUE TITLE
Google Analythics & Smartlook

### ISSUE THREAD

**Issue by JanGalek** [nittro/nittro#7]
# English
I see a big problem with changing url, when you try tracking your website with nittro and click to another page, so then google analythics didnt change it, with smartlook is the same problem.

So some ideas to fix it ?

# Czech
Vidím velký problem u změň url adres, pokud sledujeme stránku, která má implementováno nittro a klikneme na jinou stránku, tak v google analythics se adresa nezmění, stejný problém je i u smartlooku.

Nějaké nápady jak toto vyřešit ?

# EDIT:

# English:
So find small fix for Analythics:
`
    ga('set', 'page', window.location.pathname);
`
So, but with smartlook I dont know, there are not API

# Czech:
Tak Analythics jsem tak nějak vyřešil
`
    ga('set', 'page', window.location.pathname);
`

Ale s smartoolkem už nevím, ten nemá žádné API :/

**Comment by jahudka** [comment]
Well I usually have something like this in my bootstrap:

    services: {
        // ...
        page: {
            factory: 'Nittro.Page.Service()!',
            setup: [
                function() { this.on('update', function() { window.ga && window.ga('send', 'pageview'); }); }
            ]
        }
        // ...

And since the initial page load also triggers an 'update' event you can drop the `ga('send', 'pageview')` line from the GA js snippet; otherwise your code in the update event handler shouldn't call the tracking callback on the first update event. Note that if you're using the bleeding-edge nittro#master, you'd have to listen for the `savestate` and `popstate` events of the `history` service instead of the `update` event of the `page` service, but if you're still using 1.9.x, the above approach should work just fine.

As for Smartlook, they definitely _do_ have some kind of an API, they just didn't do a great job documenting it - see https://www.smartlook.com/docs/recording.html for example - that site shows that there _is_ some kind of JS API, but I couldn't find any further info and their chat was offline. So perhaps try catching them online and asking how one would go about tracking an ajax-enabled site - they'll probably give you a line of code that you're supposed to call every time the URL changes and that'll be that.
